In [18]:
# import the necessary libraries
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from hmmlearn import hmm
 


In [2]:
nltk_data = pd.read_csv("C:/Users/Gazal V/Desktop/Dowell/keywords.csv")
nltk_data

Keyword  Percentage
0            Instant Food    0.000674
1                 Instant    0.001084
2     Instant Food online    0.001280
3                    Food    0.001592
4   Instant Food products    0.001637
5                  online    0.001900
6      Instant food mixes    0.001941
7    food products online    0.002019
8         Instant Noodles    0.002118
9        Instant Mix Food    0.002185
10       Buy Instant Food    0.002322
11    instant Online Food    0.002560
12   instant mixes online    0.003192
13   Instant mix products    0.003456
14          instant mixes    0.003919
15            food online    0.003986
16          Food Products    0.004146
17      Mix Food Products    0.004331
18  Instant food delivery    0.004658
19            Buy Instant    0.005117

In [3]:
a = list(nltk_data['Keyword'])

In [4]:
texts = ' '.join(str(e) for e in a)

In [5]:
#print each word with its respective tag for first two sentences
for sent in nltk_data[:2]:
  print(nltk_data[:2])
print(tuple)

        Keyword  Percentage
0  Instant Food    0.000674
1       Instant    0.001084
        Keyword  Percentage
0  Instant Food    0.000674
1       Instant    0.001084
<class 'tuple'>


In [6]:
import pandas as pd
text= pd.read_csv("C:/Users/Gazal V/Desktop/Dowell/all/demo_5.csv")
text.head

<bound method NDFrame.head of            result_type                        id   status  \
0             metadata  64f05e420f986612e4790c25  Success   
1    search_parameters                       NaN      NaN   
2              organic                       NaN      NaN   
3              organic                       NaN      NaN   
4              organic                       NaN      NaN   
..                 ...                       ...      ...   
381   related_searches                       NaN      NaN   
382   related_searches                       NaN      NaN   
383   related_searches                       NaN      NaN   
384   related_searches                       NaN      NaN   
385   related_searches                       NaN      NaN   

                                         json_endpoint  \
0    https://serpapi.com/searches/0fe38a9c64a5b7b7/...   
1                                                  NaN   
2                                                  NaN   
3    

In [7]:
text.drop(text.iloc[:, :30], inplace=True, axis=1)

In [8]:
text.drop(text.iloc[:, 1:], inplace=True, axis=1)

In [9]:
text= text.dropna()

In [10]:
text.head()

snippet
2  Amazon.in: Instant Food. ... FREE Delivery ove...
3  Ready To Eat Meals: Buy Ready to Eat Snacks an...
4  Just order from our ready to eat food online p...
5  Be the first to know about exciting new flavor...
6  Discover a wide range of ready meals, instant ...

In [11]:
a = list(text['snippet'])

In [12]:
text = ' '.join(str(e) for e in a)

In [13]:
text

"Amazon.in: Instant Food. ... FREE Delivery over ₹499. Fulfilled by Amazon. ... As fast as 2 hours delivery on orders above ₹ 499 of Fresh items. Ready To Eat Meals: Buy Ready to Eat Snacks and Meals at India's best online shopping store. ✓Genuine Products ✓Best Offers. Just order from our ready to eat food online page at bigbasket and allow us to cater to your food cravings. Right from those chatpata snacks to full spread ... Be the first to know about exciting new flavors and offers, please enter your email address below. Discover a wide range of ready meals, instant mixes, and gourmet foods at Mirchi.com. Enjoy delicious and convenient options for quick meals and snacks. Aashirvaad best healthy instant meals ready in minutes with boiling water and includes Khatta Meetha Poha, Veggie Upma, Suji Halwa with Jaggery, ... India's Largest Traditional Home-made Food Products Global Online Store since 2012. Traditional Bakshanam; Spice Products; Instant ... Shop ready-to-eat food products o

In [14]:
# Define the state space
#texts = ["Sunny", "Rainy"]
n_texts = len(texts)
print('Number of hidden states :',n_texts)
# Define the observation space
#observations = ["Dry", "Wet"]
n_observations = len(text)
print('Number of observations  :',n_observations)

Number of hidden states : 318
Number of observations  : 23814


In [16]:
# Define the initial state distribution
state_probability = np.array([0.6, 0.4])
print("State probability: ", state_probability)
  
# Define the state transition probabilities
transition_probability = np.array([[0.7, 0.3],
                                   [0.3, 0.7]])
print("\nTransition probability:\n", transition_probability)
# Define the observation likelihoods
emission_probability= np.array([[0.9, 0.1],
                                 [0.2, 0.8]])
print("\nEmission probability:\n", emission_probability)

State probability:  [0.6 0.4]

Transition probability:
 [[0.7 0.3]
 [0.3 0.7]]

Emission probability:
 [[0.9 0.1]
 [0.2 0.8]]


In [20]:
model = hmm.CategoricalHMM(n_components=n_texts)
model.startprob_ = state_probability
model.transmat_ = transition_probability
model.emissionprob_ = emission_probability

In [21]:
# Define the sequence of observations
observations_sequence = np.array([0, 1, 0, 1, 0, 0]).reshape(-1, 1)
observations_sequence

array([[0],
       [1],
       [0],
       [1],
       [0],
       [0]])

In [22]:
# Predict the most likely sequence of hidden states
hidden_states = model.predict(observations_sequence)
print("Most likely hidden states:", hidden_states)

ValueError: startprob_ must have length n_components

In [23]:
log_probability, hidden_states = model.decode(observations_sequence,
                                              lengths = len(observations_sequence),
                                              algorithm ='viterbi' )
  
print('Log Probability :',log_probability)
print("Most likely hidden states:", hidden_states)

ValueError: startprob_ must have length n_components

In [24]:
# Plot the results
sns.set_style("whitegrid")
plt.plot(hidden_states, '-o', label="Hidden State")
plt.xlabel('Time step')
plt.ylabel('Most Likely Hidden State')
plt.title("Sunny or Rainy")
plt.legend()
plt.show()

NameError: name 'hidden_states' is not defined

In [ ]:
#

In [ ]:
#